### ISSUE TITLE
Is there a headless way to extract packed client?

### ISSUE THREAD

**Issue by Hpmason** [lcdr/utils#3]
I'm trying to work on automating the DLU server build setup and was wondering if there's a headless (no GUI) method to extract the content?

**Comment by lcdr** [comment]
Not with the tools in this repo. pkextractor was always meant as a GUI for browsing PK archives, not as a command line tool. There may be other tools that can do this, but I'm not aware of them.

FWIW, I didn't expect this tool to be listed in the DLU readme, or for so many people to try and install DLU, otherwise I would have mentioned to the other devs that it's not ideal for an automated setup.

**Comment by Hpmason** [comment]
That's understandable, I didn't realized you were unaware of this added to the README.

**Comment by lcdr** [comment]
Yeah, I just do network protocol research, I'm not at all involved with the main codebase or the setup. I myself think it's unnecessarily complicated right now. Anyway, the DLU team is working on making it easier as we speak.
